[pytest]
addopts = -s --html=reports/login_report.html --self-contained-html
markers =
    smoke:冒烟测试
    login:登录模块测试
testpaths = scripts
python_files = test_login_params_log.py
python_classes = Test*
python_functions = test*